spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
  datasource:
    hikari:
      leak-detection-threshold: 5000
      maximum-pool-size: 20
      max-lifetime: 900000
    url: ${DB_URL:jdbc:postgresql://db:5432/prommt-postgres}
    username: ${DB_USERNAME:prommt-postgres}
    password: ${DB_PASSWORD:prommt-postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        show_sql: false
